// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCustomPlan'](arg1, arg2, arg3);
}

export function CreateGameMode(arg1) {
  return window['go']['main']['App']['CreateGameMode'](arg1);
}

export function CreateOfficeMode(arg1) {
  return window['go']['main']['App']['CreateOfficeMode'](arg1);
}

export function DeletePlan(arg1) {
  return window['go']['main']['App']['DeletePlan'](arg1);
}

export function GetCurrentPlan() {
  return window['go']['main']['App']['GetCurrentPlan']();
}

export function GetPlanSettings(arg1) {
  return window['go']['main']['App']['GetPlanSettings'](arg1);
}

export function IsSystemPlan(arg1) {
  return window['go']['main']['App']['IsSystemPlan'](arg1);
}

export function ListPlans() {
  return window['go']['main']['App']['ListPlans']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RenamePlan(arg1, arg2) {
  return window['go']['main']['App']['RenamePlan'](arg1, arg2);
}

export function SetBalanced() {
  return window['go']['main']['App']['SetBalanced']();
}

export function SetHighPerformance() {
  return window['go']['main']['App']['SetHighPerformance']();
}

export function SetPlanByGUID(arg1) {
  return window['go']['main']['App']['SetPlanByGUID'](arg1);
}

export function SetPowerSaver() {
  return window['go']['main']['App']['SetPowerSaver']();
}

export function SetSettingValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSettingValue'](arg1, arg2, arg3, arg4);
}
