// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCustomPlan(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function CreateGameMode(arg1:string):Promise<string>;

export function CreateOfficeMode(arg1:string):Promise<string>;

export function DeletePlan(arg1:string):Promise<void>;

export function GetCurrentPlan():Promise<string>;

export function GetPlanSettings(arg1:string):Promise<Array<main.PowerSetting>>;

export function IsSystemPlan(arg1:string):Promise<boolean>;

export function ListPlans():Promise<Array<main.PowerPlan>>;

export function OpenURL(arg1:string):Promise<void>;

export function RenamePlan(arg1:string,arg2:string):Promise<void>;

export function SetBalanced():Promise<void>;

export function SetHighPerformance():Promise<void>;

export function SetPlanByGUID(arg1:string):Promise<void>;

export function SetPowerSaver():Promise<void>;

export function SetSettingValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
